server:
  port: 8083
  address: localhost
  
facebook:
  client:
    clientId: 229148647510486
    clientSecret: c57478a97a27bc9c2bb14d4e12d1a941
    accessTokenUri: https://graph.facebook.com/oauth/access_token
    userAuthorizationUri: https://www.facebook.com/dialog/oauth
    tokenName: oauth_token
    callbackurl: http://${server.address}:${server.port}/pl-facebook/callback    
    userInfoUri: https://graph.facebook.com/me

logging:
  level:
    org.springframework.web: ERROR
    com.pl.facebook: DEBUG
  pattern:
    console: "%d{yyyy-MM-dd HH:mm:ss} PlanetLoop-FacebookCore - %msg%n"
    file: "%d{yyyy-MM-dd HH:mm:ss} [%thread] %-5level %logger{36} - %msg%n"
  file: /Users/mkyong/application.log    
