#%RAML 0.8
title: Planetloop-facebook-system-apis
baseUri: http://localhost:8087/integration/facebook
mediaType: application/json
schemas: 
  - user-details : | 
      {
         "type": "object",
         "properties": {
            "id": {
              "type": "string"
             },
            "firstName": {
              "type": "string"
             },
            "lastName": {
              "type": "string"
             },
            "displayName": {
              "type": "string"
             },
            "gender": {
              "type": "string"
             },
            "aboutMe": {
              "type": "string"
             },
            "dateOfBirth": {
              "type": "string"
            },
            "memberSince": {
              "type": "string"
            },
            "isActive" : {
              "type": "string"
            },
            "address": {
              "type": "array",
              "items": {
                  "type": "object",
                  "properties": {
                     "city": {
                       "type": "string"
                      },
                     "state": {
                       "type": "string"
                      },
                     "country": {
                       "type": "string"
                      }
                  }
              }
            }
          }  
      }        
  - user-videos : |
      {
         "$schema": "http://json-schema.org/draft-04/schema#",
         "type": "object",
         "properties": {
           "userid": {
              "type": "string"
           },
           "videos": {
              "type": "array",
                "items": {
                   "type": "object",
                      "properties": {
                        "videoId": {
                           "type": "string"
                         },
                        "embedHtml": {
                          "type": "string"
                        },
                        "content_category": {
                          "type": "string"
                        },
                        "description": {
                          "type": "string"
                        },
                        "thumb": {
                          "type": "string"
                        },
                        "title": {
                          "type": "string"
                        },
                        "likeCounts": {
                           "type": "string"
                        },
                        "shareCount": {
                           "type": "string"
                        },
                        "uploadTimestamp": {
                          "type": "string"
                        }
                      }
                  }
              }
          }
        }
  - videos : |
      {
        "$schema": "http://json-schema.org/draft-04/schema#",
        "type": "object",
        "properties": {
             "videos": {
               "type": "array",
                    "items": {
                          "type": "object",
                          "properties": {
                              "videoId": {
                                 "type": "string"
                              },
                              "embedHtml": {
                                 "type": "string"
                              },
                              "content_category": {
                                 "type": "string"
                              },
                              "description": {
                                 "type": "string"
                              },
                              "thumb": {
                                 "type": "string"
                              },
                              "title": {
                                 "type": "string"
                              },
                              "likeCounts": {
                                 "type": "string"
                              },
                              "shareCount": {
                                 "type": "string"
                              },
                              "uploadTimestamp": {
                                 "type": "string"
                              }
                            }
                        }
                      }
                    }
                }      
            
/user:
  displayName: userDetails
  get:
    description: This will give the details of the user who has logged into the system and we are having the token for the same
    queryParameters: 
      userId:
        type: string
        required: true
        example: 123
    responses: 
      200:
        description: User details
        body: 
          application/json:
            schema: user-details
            example: |
              {
                "dateOfBirth": "19-Nov-1990",
                "memberSince": "Jan 2016",
                "aboutMe": "et eu exercitation",
                "displayName": "tempor dolor",
                "lastName": "nulla veniam",
                "address": [
                    {
                      "city": "ea pariatur commodo dolor",
                      "state": "deserunt",
                      "country": "consectetur dolor veniam in dolore"
                    },
                    {
                      "city": "anim",
                      "country": "nostrud cillum adipisicing dolor"
                    }
                ],
                "id": "1234",
                "gender": "male"
              }
  post:
    description: api for creating the user into the system
    body: 
      application/json:
        schema: user-details
        example: |
              {
                "dateOfBirth": "19-Nov-1990",
                "memberSince": "Jan 2016",
                "aboutMe": "et eu exercitation",
                "displayName": "tempor dolor",
                "lastName": "nulla veniam",
                "address": [
                    {
                      "city": "ea pariatur commodo dolor",
                      "state": "deserunt",
                      "country": "consectetur dolor veniam in dolore"
                    },
                    {
                      "city": "anim",
                      "country": "nostrud cillum adipisicing dolor"
                    }
                ],
                "id": "1234",
                "gender": "male"
              }
    responses: 
        200:
         description: User details
         body: 
          application/json:
            schema: user-details
            example: |
              {
                "dateOfBirth": "19-Nov-1990",
                "memberSince": "Jan 2016",
                "aboutMe": "et eu exercitation",
                "displayName": "tempor dolor",
                "lastName": "nulla veniam",
                "address": [
                    {
                      "city": "ea pariatur commodo dolor",
                      "state": "deserunt",
                      "country": "consectetur dolor veniam in dolore"
                    },
                    {
                      "city": "anim",
                      "country": "nostrud cillum adipisicing dolor"
                    }
                ],
                "id": "1234",
                "gender": "male"
              } 
           
          
              
/uploadedVideos:
   displayName: uploadedVideos
   get:
     description: This will list out the vidoes uploaded by the user
     queryParameters: 
       userId:
        type: string
        required: true
       startTime:
         type: string
         required: true
         example: 20160101120000
       endTime:
         type: string
         required: true
         example: 20160101120000       
     responses: 
       200:
         body: 
           application/json:
             schema: user-videos
             example: |
               {
                "userid": "1234",
                "videos": [
                    {
                      "videoId": "1",
                      "embedHtml": "https://www.facebook.com/video/embed?video_id=102421750266921",
                      "content_category": "music",
                      "description": "Rock concert by beyonce",
                      "thumb": "121212",
                      "title": "Rock concert by beyonce",
                      "likeCounts": "23",
                      "shareCount": "12",
                      "uploadTimestamp": "20160202121212111"
                    },
                    {
                      "videoId": "2",
                      "embedHtml": "https://www.facebook.com/video/embed?video_id=10242130266921",
                      "content_category": "news",
                      "description": "Rock concert by beyonce",
                      "thumb": "121212",
                      "title": "Rock concert by beyonce",
                      "likeCounts": "23",
                      "shareCount": "12",
                      "uploadTimestamp": "20160302121212111"
                    }
                  ]
                }                
/postVideo:
   displayName: postVideo
   post:
      description: This method will enable us to post videos on facebook
/recommnededVideos:
   displayName: recommendedVideos
   get:
      description: This method will enable us to get the recommneded videos based on user's interrests
      queryParameters: 
        userId:
          type: string
          description: user id of the user whose recommended videso needs to be extracted
          required: true
          example: 123
      responses: 
       200:
         body: 
           application/json:
             schema: user-videos
             example: |
               {
                "userid": "1234",
                "videos": [
                    {
                      "videoId": "1",
                      "embedHtml": "https://www.facebook.com/video/embed?video_id=102421750266921",
                      "content_category": "music",
                      "description": "Rock concert by beyonce",
                      "thumb": "121212",
                      "title": "Rock concert by beyonce",
                      "likeCounts": "23",
                      "shareCount": "12",
                      "uploadTimestamp": "20160202121212111"
                    },
                    {
                      "videoId": "2",
                      "embedHtml": "https://www.facebook.com/video/embed?video_id=10242130266921",
                      "content_category": "news",
                      "description": "Rock concert by beyonce",
                      "thumb": "121212",
                      "title": "Rock concert by beyonce",
                      "likeCounts": "23",
                      "shareCount": "12",
                      "uploadTimestamp": "20160302121212111"
                    }
                  ]
                } 
/authorize:
   displayName: authorize
   get:
    description: Authorizes the user
    queryParameters: 
      userId:
        type: string
        description: userId
    responses: 
          200:
            description: Response will have the is_active flag
            body: 
              application/json:
                schema: user-details
                example: |
                  {
                    "dateOfBirth": "19-Nov-1990",
                    "memberSince": "Jan 2016",
                    "aboutMe": "et eu exercitation",
                    "displayName": "tempor dolor",
                    "lastName": "nulla veniam",
                    "address": [
                     {
                       "city": "ea pariatur commodo dolor",
                       "state": "deserunt",
                       "country": "consectetur dolor veniam in dolore"
                     },
                     {
                       "city": "anim",
                       "country": "nostrud cillum adipisicing dolor"
                     }
                    ],
                    "id": "1234",
                    "gender": "male",
                    "isActive": "true"
                  }
   
/unauthorize:
   displayName: unauthorize
   get:
    queryParameters: 
      userId: 
       type: string
       description: user id which needs to be deassociated 
    responses: 
          200:
            description: Response will have the is_active flag
            body: 
              application/json:
                schema: user-details
                example: |
                  {
                    "dateOfBirth": "19-Nov-1990",
                    "memberSince": "Jan 2016",
                    "aboutMe": "et eu exercitation",
                    "displayName": "tempor dolor",
                    "lastName": "nulla veniam",
                    "address": [
                     {
                       "city": "ea pariatur commodo dolor",
                       "state": "deserunt",
                       "country": "consectetur dolor veniam in dolore"
                     },
                     {
                       "city": "anim",
                       "country": "nostrud cillum adipisicing dolor"
                     }
                    ],
                    "id": "1234",
                    "gender": "male",
                    "isActive": "false"
                  } 
      
              